# Generated by Django 5.1.1 on 2024-09-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image__upload', '0003_transactions_remove_imageupload_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=10, unique=True)),
                ('drug_name', models.CharField(max_length=255)),
                ('recall_date', models.DateField(blank=True, null=True)),
                ('reason_for_recall', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
