# Generated by Django 5.1.1 on 2024-09-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image__upload', '0004_drugrecord_delete_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-09-20 12:00:00'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TextExtraction',
        ),
    ]
