# Generated by Django 5.1.1 on 2024-09-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image__upload', '0006_imageupload_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugrecord',
            name='recall_status',
            field=models.CharField(default='Recalled', max_length=50),
        ),
    ]
