# Generated by Django 5.1.1 on 2024-09-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacy_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='reported',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
