# Generated by Django 5.0.7 on 2024-09-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_remove_pharmacy_pharmacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='reported',
            field=models.BooleanField(max_length=100),
        ),
    ]
