# Generated by Django 5.0.7 on 2024-10-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0005_rename_address_pharmacy_pharmacyname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='pharmacyName',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='county',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='town',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='license_status',
            field=models.CharField(default='Kiruki', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(default='Goodelife', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='reported',
            field=models.BooleanField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
