# Generated by Django 5.1.1 on 2024-09-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
