# Generated by Django 5.1.1 on 2024-09-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPBData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recall_date', models.DateField()),
                ('recall_reference_number', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('inn_name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=255)),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('recall_reason', models.TextField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
