# Generated by Django 5.1.1 on 2024-09-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('pharmacy_name', models.CharField(max_length=100)),
                ('registration_number', models.PositiveSmallIntegerField()),
                ('license_status', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
            ],
        ),
    ]
