# Generated by Django 5.1.1 on 2024-09-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='street',
            new_name='town',
        ),
    ]
