# Generated by Django 5.1.1 on 2024-09-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_pharmacy_pharmacy_id_pharmacy_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='pharmacy_id',
        ),
    ]
