# Generated by Django 5.1.1 on 2024-09-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image__upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
