# Generated by Django 5.1.1 on 2024-09-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image__upload', '0002_imageupload_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='extracted_text',
        ),
    ]
